version: "3.9"

services:
  validator-1:
    container_name: validator-1
    image: rust-blockchain:latest
    environment:
      - RUST_LOG=debug
      - VALIDATOR_CALLBACK=validator-1
      - VALIDATOR_SK=validator-1_private_key
      - VALIDATOR_PK=validator-1_public_key
    
  validator-2:
    container_name: validator-2
    image: rust-blockchain:latest
    environment:
      - RUST_LOG=debug
      - VALIDATOR_CALLBACK=validator-2
      - VALIDATOR_SK=validator-2_private_key
      - VALIDATOR_PK=validator-2_public_key
      - REMOTE_VALIDATOR=validator-1
    depends_on:
      - validator-1
    
  validator-3:
    container_name: validator-3
    image: rust-blockchain:latest
    environment:
      - RUST_LOG=debug
      - VALIDATOR_CALLBACK=validator-3
      - VALIDATOR_SK=validator-3_private_key
      - VALIDATOR_PK=validator-3_public_key
      - REMOTE_VALIDATOR=validator-1
    depends_on:
      - validator-2
      - validator-1